name: CI
on: [push, pull_request, workflow_dispatch]
env:
  ProjectName: CertbotAliyunDns

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: 
          - win-x64
          - win-arm64
          - win-x86
          - linux-x64
          - linux-musl-x64
          - linux-arm64
          - linux-musl-arm64
          - linux-arm
          - linux-musl-arm
          - osx-x64
          - osx-arm64
    env:
      NET_TFM: net6.0
      Configuration: Release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build .NET App
      shell: pwsh
      run: .\build.ps1 ${{ matrix.rid }}

    - name: Upload .NET App
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}-${{ matrix.rid }}
        path: ${{ env.ProjectName }}/bin/${{ env.Configuration }}/${{ env.NET_TFM }}/${{ matrix.rid }}/publish/
